version: '3' # docker-composeのversion
services:
  app:
    build: ./App/
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
      - nginx
      - elastic-search
  nginx:
    build: ./Nginx/
  mysql:
    build: ./Mysql/
  redis:
    build: ./Redis/
  elastic-search:
    build: ./ElasticSearch/
