version: '3'
services:
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  app:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - mysql
  nginx:
    build: containers/nginx
    ports:
      - '80:80'
    depends_on:
      - app
