version: '3'
services:
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  app:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - mysql
